language : shell

os : windows

install :
  # install anaconda
  - travis_wait 20 choco install anaconda3 --params '"/JustMe /D:c:\Users\travis"'
  - CONDA_PATH=/c/Users/travis/Anaconda3
  # install vscode
  - choco install vscode
  - . ~/.bashrc
  # check PATH environment variable
  - echo $PATH
  # expected location of the vscode
  - VSCODE_PATH="/c/Program Files/Microsoft VS Code/bin"
  # add vscode path to PATH
  - export PATH=$VSCODE_PATH:$PATH
  - echo $PATH
  - which code
  - which python
  - hash -r
  - which code
  - which python
  # install python extension for vscode
  - code --install-extension ms-python.python
  - code --list-extensions
  # install git for Windows 2.21
  - choco install git.install

script :
  - $CONDA_PATH/Scripts/pytest && exit

notifications : 
  email :
    - kangwon.lee.edu@gmail.com
