language : shell

services :
  - docker

os : windows

before_install:
  - docker pull --platform=windows continuumio/anaconda3 
  - docker run -it -v $(pwd):/config-windows continuumio/anaconda3 /bin/bash
  - docker ps -a
  - docker run continuumio/anaconda3 /bin/bash -c "cd /config-windows; nosetests"

install:
  - choco install vscode
  - which code
  - code --install-extension ms-python.python
  - code --list-extensions

script :
  - $CONDA_PATH/Scripts/nosetests && exit

notifications : 
  email :
    - kangwon.lee.edu@gmail.com
