language : generic

os : windows

install :
  # install anaconda
  - choco install anaconda3 --params '"/JustMe /D:c:\MyTools"'
  - choco install vscode
  - code --install-extension ms-python.python
  - code --extensions-dir
  