language : shell

os : windows

install :
  # install anaconda
  - travis_wait choco install anaconda3 --params '"/JustMe /D:c:\Users\travis"'
  # install vscode
  - choco install vscode
  - . ~/.bashrc
  # check PATH environment variable
  - echo $PATH
  # expected location of the vscode
  - VSCODE_PATH="/c/Program Files/Microsoft VS Code/bin"
  # add vscode path to PATH
  - export PATH=$VSCODE_PATH:$PATH
  - echo $PATH
  - which code
  # install python extension for vscode
  - code --install-extension ms-python.python
  - code --extensions-dir

script :
  - python -m nose

notifications : 
  email :
    - kangwon.lee.edu@gmail.com
