git config --global gitflow.prefix.feature "feature/"
git config --global gitflow.prefix.bugfix "bugfix/"
git config --global gitflow.prefix.release "release/"
git config --global gitflow.prefix.hotfix "hotfix/"
git config --global gitflow.prefix.support "support/"
